---
title: "Examples with ggplot2"
output: html_document
---

# Brief overview of `ggplots2` package

All `ggplot` functions must have at least three components:

*  **data frame**: data associated with the plot. 
*  **geom**: to determine the type of geometric shape used to display the data, such as line, bar, point, or area. Note that you can use different data in different geoms by 
*  **aes**: to determine how variables in the data are _mapped_ to visual properties (aesthetics) of geoms. This can include x position, y position, color, shape, fill, and size.
  + If the `aes` statement is included in the `ggplot` command, the mapping will be available to any `geom`s used
  + If you need a variable mapped to just a specific `geom`, you can include it in an `aes` mapping for a specific geom. (You can also do something similar with the `data` option if you need to plot multiple data sources on the same display. However, it is generally better to think about structuring your dataset )

# Practice Problems with ggplots2

For this set of exercises we will be using a slightly larger version of the Stat 113 first day survey data. It is in the file `stat113_f18_s19.csv` (and contains two semesters of surveys).

## Univariate Analyses

We will begin with a series of basic displays for univariate analyses.

* Investigate the distribution of the amount of TV watched (in hours per week) by Stat 113 students.

* Use another display to investigate the distribution of the amount of TV watched (in hours per week) by Stat 113 students.

* Combine the geoms from the previous part onto the same plot.


* Pick your favorite chart of the three and play around with a few options such as color, fill, linetype, and alpha. 



* Pick another numeric variable to explore. Play around with themes, coordinate systems, and labels.


* Pick a categorical variable and make a bar chart.


## Multivariate Analyses

We will investigate a few research questions involving two variables and produce graphics of the following. (Note: You may need to use different sets of variables for some of them.)

* Side-by-side boxplots and/or violin plots

* Scatterplot

* Scatterplot + Smoother

* Scatterplot + Linear Smoother

* Stacked Bar Chart

* Faceted Density plots

After getting a "basic plot" constructed for each, investigate options to customize and "clean up" the plots. Try to make them look nice.


* Recreate "example.png" (from the T drive)

* Use Class as a factor (categorical variable) instead of a numerical variable

## Further Practice

The document `06-data_visualization` contains more detailed notes related to the grammar of graphics (using `ggplots2`). Please note that a set of Exercises will have you working through those from that document. You might as well get started on them early.